title: Interactive Badge
hero_image: images/interactive-badge.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
description: Learn how to make a badge that shows your mood.
original_url: https://codeclubprojects.org/en-GB/microbit/interactive-badge
interests: ''
technologies: ''
site_areas: codeclub, microbit
steps:
- title: Introduction
- title: Displaying an image
- title: Displaying a happy face
- title: 'Challenge: Displaying a sad face'
- title: Creating a simple animation
- title: 'Challenge: Create your own interactive badge!'

