---
title: इंटरेक्टिव बैज
hero_image: images/interactive-badge.png
theme: फ़िरोज़ी
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-1, community-0
description: एक बैज बनाएँ जो आपके मूड को दिखाता है
original_url: https://codeclubprojects.org/en-GB/microbit/interactive-badge
interests: वियरेबल टेक्नोलॉजी
technologies: microbit
site_areas: प्रोजेक्ट
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
  - 
    title: भूमिका
  - 
    title: एक छवि प्रदर्शित करना
  - 
    title: एक खुश चेहरा प्रदर्शित करना
  - 
    title: 'चुनौती: एक उदास चेहरा प्रदर्शित करना'
  - 
    title: एक साधारण एनिमेशन बनाना
  - 
    title: 'चुनौती: अपना खुद का इंटरेक्टिव बैज बनाएँ!'
