---
title: Bathodyn rhyngweithiol
hero_image: images/interactive-badge.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-1, community-0
description: Gwnewch fathodyn sy'n dangos eich hwyliau
original_url: https://codeclubprojects.org/en-GB/microbit/interactive-badge
interests: wearable-technology
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Cyflwyniad
  completion: engaged
- title: Dangos delwedd
- title: Dangos wyneb hapus
- title: 'Her: Dangos wyneb trist'
- title: Creu animeiddiad syml
  completion: internal
- title: 'Her: Creu eich bathodyn rhyngweithiol eich hun!'
