---
title: Interactive badge
hero_image: images / interactive-badge.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disseny-0, programació-1, phys-comp-0, fabricació-1, comunitat-0
description: Make a badge that shows your mood
original_url: https://codeclubprojects.org/en-GB/microbit/interactive-badge
interests: wearable-technology
technologies: microbit
site_areas: projectes
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps:
  - 
    title: Introducció
  - 
    title: Displaying an image
  - 
    title: Displaying a happy face
  - 
    title: 'Challenge: Displaying a sad face'
  - 
    title: Creating a simple animation
  - 
    title: 'Challenge: Create your own interactive badge!'
