---
title: Διαδραστικό έμβλημα/σήμα
hero_image: images/interactive-badge.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-1, community-0
description: Φτιάξε ένα έμβλημα/σήμα που δείχνει τη διάθεσή σoυ
original_url: https://codeclubprojects.org/en-GB/microbit/interactive-badge
interests: wearable-technology
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3
last_tested: 2019-03-06
steps:
- title: Εισαγωγή
  completion: engaged
- title: Εμφάνιση μιας εικόνας
- title: Εμφάνιση ενός χαμογελαστού προσώπου
- title: 'Πρόκληση: Εμφάνιση ενός λυπημένου προσώπου'
- title: Δημιουργία απλής κινούμενης εικόνας
  completion: internal
- title: 'Πρόκληση: Δημιούργησε το δικό σου διαδραστικό έμβλημα/σήμα!'
